-- Migration 007: Expand species catalog with new species, varieties, and watering_multiplier in growth phases
-- 1. Update existing species growth_phases to include watering_multiplier
-- 2. Add new indoor plants
-- 3. Add new succulents
-- 4. Add new edible plants (vegetables, herbs, fruit trees)
-- 5. Add new ornamental outdoor plants
-- 6. Add tomato varieties (cherry, RAF) and cannabis autos/hybrids

-- ============================================================================
-- 1. UPDATE EXISTING SPECIES: Add watering_multiplier to growth_phases
-- ============================================================================

-- Indoor plants
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.7,"description":"Esqueje o planta muy joven, mantener humedo"},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.85,"description":"Crecimiento activo, hojas sin agujeros"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Hojas fenestradas, crecimiento estable"}]'::jsonb WHERE id = 'local_monstera';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_pothos';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_snake_plant';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_peace_lily';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_ficus';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_aloe';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":6,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_spider_plant';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_calathea';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_philodendron';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_zz_plant';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.7,"description":"Riego mas frecuente pero poco"},{"stage":"juvenile","duration_months":36,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_cactus';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_echeveria';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_jade';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6,"description":"Plantula fragil, riego suave frecuente"},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.75,"description":"Crecimiento vegetativo rapido"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Fructificacion, riego profundo"}]'::jsonb WHERE id = 'local_tomato';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6,"description":"Mantener sustrato humedo sin encharcar"},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Cosechar antes de que florezca"}]'::jsonb WHERE id = 'local_basil';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_rosemary';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_lavender';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_mint';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mas agua durante floracion"}]'::jsonb WHERE id = 'local_rose';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.8,"description":"Planta joven, raices en desarrollo"},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9,"description":"Crece hojas, prepara floracion"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Florece ciclicamente"}]'::jsonb WHERE id = 'local_orchid';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_fiddle_leaf';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_rubber_plant';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_boston_fern';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_dracaena';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_croton';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":6,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_pilea';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_pepper';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.65,"description":"Estolones o plantula, mantener humedo"},{"stage":"juvenile","duration_months":3,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mas agua durante fructificacion"}]'::jsonb WHERE id = 'local_strawberry';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":6,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_succulent';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":6,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_bamboo';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_anthurium';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":4,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_geranium';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6,"description":"Germinacion lenta (2-4 semanas)"},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb WHERE id = 'local_parsley';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Cosechar antes de que espigue"}]'::jsonb WHERE id = 'local_lettuce';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.6,"description":"Pre-bonsai, necesita riego frecuente"},{"stage":"juvenile","duration_months":60,"watering_multiplier":0.8,"description":"Formacion, podas frecuentes"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mantenimiento"}]'::jsonb WHERE id = 'local_bonsai';

-- Update cannabis parent + all varieties
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5,"description":"Germinacion, riego muy suave"},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo: riego creciente"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion: maximo consumo de agua"}]'::jsonb WHERE id = 'local_cannabis';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7,"description":"Vegetativo 4-5 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 7-8 semanas"}]'::jsonb WHERE id = 'local_cannabis_critical';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-6 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 8-9 semanas"}]'::jsonb WHERE id = 'local_cannabis_og_kush';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7,"description":"Vegetativo 4-5 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 7-8 semanas"}]'::jsonb WHERE id = 'local_cannabis_northern_lights';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-6 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 8-9 semanas"}]'::jsonb WHERE id = 'local_cannabis_gorilla_glue';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7,"description":"Vegetativo 4-5 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 7-8 semanas"}]'::jsonb WHERE id = 'local_cannabis_blue_cheese';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-6 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 8-9 semanas"}]'::jsonb WHERE id = 'local_cannabis_granddaddy_purple';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 6-8 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 10-12 semanas"}]'::jsonb WHERE id = 'local_cannabis_amnesia_haze';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-7 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 9-10 semanas"}]'::jsonb WHERE id = 'local_cannabis_jack_herer';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 6-8 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 10-11 semanas"}]'::jsonb WHERE id = 'local_cannabis_sour_diesel';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-6 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 8-9 semanas"}]'::jsonb WHERE id = 'local_cannabis_white_widow';
UPDATE species_catalog SET growth_phases = '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7,"description":"Vegetativo 5-6 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 8-9 semanas"}]'::jsonb WHERE id = 'local_cannabis_gelato';

-- ============================================================================
-- 2. INSERT NEW INDOOR SPECIES
-- ============================================================================

INSERT INTO species_catalog (id, common_name, scientific_name, category, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, drought_tolerant, humidity_loving, is_edible, growth_phases) VALUES
('local_alocasia', 'Alocasia', 'Alocasia amazonica', 'indoor', 5, 3, 4, 6, 'medium', 15, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.65,"description":"Bulbo recien plantado, riego moderado"},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_maranta', 'Maranta (planta de la oracion)', 'Maranta leuconeura', 'indoor', 5, 3, 2, 5, 'low', 15, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":10,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_peperomia', 'Peperomia', 'Peperomia obtusifolia', 'indoor', 10, 7, 3, 6, 'medium', 12, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_dieffenbachia', 'Diefembaquia', 'Dieffenbachia seguine', 'indoor', 5, 4, 3, 6, 'medium', 12, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_schefflera', 'Cheflera', 'Schefflera arboricola', 'indoor', 7, 5, 4, 7, 'medium', 10, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_begonia', 'Begonia', 'Begonia rex', 'indoor', 5, 3, 3, 6, 'medium', 12, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_tradescantia', 'Tradescantia', 'Tradescantia zebrina', 'indoor', 5, 3, 4, 7, 'medium', 8, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":4,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_hoya', 'Hoya', 'Hoya carnosa', 'indoor', 10, 7, 4, 6, 'medium', 10, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Florece en racimos, no mover"}]'::jsonb),
('local_ctenanthe', 'Ctenanthe', 'Ctenanthe burle-marxii', 'indoor', 5, 3, 2, 5, 'low', 15, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":10,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_yucca', 'Yuca', 'Yucca elephantipes', 'indoor', 10, 7, 5, 10, 'high', 0, 40, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_strelitzia', 'Ave del paraiso', 'Strelitzia reginae', 'indoor', 7, 5, 5, 8, 'high', 8, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.7,"description":"Crecimiento lento, no florece aun"},{"stage":"juvenile","duration_months":36,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Florece a partir de 4-5 anios"}]'::jsonb),
('local_aspidistra', 'Aspidistra', 'Aspidistra elatior', 'indoor', 10, 7, 1, 4, 'low', 0, 35, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":24,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_kentia', 'Kentia', 'Howea forsteriana', 'indoor', 7, 5, 3, 6, 'medium', 8, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":36,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_string_of_pearls', 'Collar de perlas', 'Senecio rowleyanus', 'succulent', 14, 10, 4, 6, 'high', 8, 35, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.75},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 3. INSERT NEW SUCCULENTS
-- ============================================================================

INSERT INTO species_catalog (id, common_name, scientific_name, category, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, drought_tolerant, humidity_loving, is_edible, growth_phases) VALUES
('local_haworthia', 'Haworthia', 'Haworthia fasciata', 'succulent', 14, 10, 3, 6, 'medium', 5, 35, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":12,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_lithops', 'Piedras vivas', 'Lithops spp.', 'succulent', 30, 21, 5, 10, 'full_sun', 5, 40, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.7,"description":"Riego con cuidado, muy sensibles"},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"No regar durante muda de hojas"}]'::jsonb),
('local_sedum', 'Sedum', 'Sedum morganianum', 'succulent', 14, 10, 5, 8, 'high', 5, 35, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":3,"watering_multiplier":0.8},{"stage":"juvenile","duration_months":8,"watering_multiplier":0.9},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 4. INSERT NEW EDIBLE PLANTS
-- ============================================================================

INSERT INTO species_catalog (id, common_name, scientific_name, category, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, drought_tolerant, humidity_loving, is_edible, hot_weather_multiplier, growth_phases) VALUES
('local_cucumber', 'Pepino', 'Cucumis sativus', 'outdoor', 2, 1, 6, 10, 'full_sun', 15, 35, FALSE, TRUE, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mucha agua durante fructificacion"}]'::jsonb),
('local_zucchini', 'Calabacin', 'Cucurbita pepo', 'outdoor', 2, 1, 6, 10, 'full_sun', 12, 35, FALSE, FALSE, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_eggplant', 'Berenjena', 'Solanum melongena', 'outdoor', 2, 1, 6, 10, 'full_sun', 15, 35, FALSE, FALSE, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_cilantro', 'Cilantro', 'Coriandrum sativum', 'outdoor', 3, 2, 4, 6, 'medium', 5, 28, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Se espiga rapido con calor"}]'::jsonb),
('local_thyme', 'Tomillo', 'Thymus vulgaris', 'outdoor', 10, 7, 6, 10, 'full_sun', -10, 35, TRUE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":6,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_oregano', 'Oregano', 'Origanum vulgare', 'outdoor', 7, 5, 6, 10, 'full_sun', -10, 35, TRUE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":4,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_chives', 'Cebollino', 'Allium schoenoprasum', 'outdoor', 4, 3, 4, 8, 'medium', -15, 35, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":4,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_spinach', 'Espinaca', 'Spinacia oleracea', 'outdoor', 2, 2, 3, 6, 'medium', -5, 25, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Cosechar antes de que espigue"}]'::jsonb),
('local_pea', 'Guisante', 'Pisum sativum', 'outdoor', 3, 2, 5, 8, 'full_sun', -2, 25, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mas agua durante floracion"}]'::jsonb),
('local_garlic', 'Ajo', 'Allium sativum', 'outdoor', 7, 5, 6, 10, 'full_sun', -10, 35, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":4,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.2,"description":"Reducir riego antes de cosechar"}]'::jsonb),
('local_onion', 'Cebolla', 'Allium cepa', 'outdoor', 4, 3, 6, 10, 'full_sun', -5, 35, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":2,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":3,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.3,"description":"Dejar de regar 2 semanas antes de cosechar"}]'::jsonb),
('local_carrot', 'Zanahoria', 'Daucus carota', 'outdoor', 3, 2, 5, 8, 'full_sun', -5, 35, FALSE, FALSE, TRUE, 0.7, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6,"description":"Mantener humedo para germinacion"},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 5. INSERT NEW ORNAMENTAL / FRUIT TREES
-- ============================================================================

INSERT INTO species_catalog (id, common_name, scientific_name, category, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, drought_tolerant, humidity_loving, is_edible, growth_phases) VALUES
('local_hydrangea', 'Hortensia', 'Hydrangea macrophylla', 'outdoor', 4, 2, 3, 6, 'medium', -10, 35, FALSE, TRUE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mucha agua en verano"}]'::jsonb),
('local_jasmine', 'Jazmin', 'Jasminum officinale', 'outdoor', 5, 3, 5, 8, 'high', -5, 35, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":4,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_bougainvillea', 'Buganvilla', 'Bougainvillea glabra', 'outdoor', 7, 5, 6, 12, 'full_sun', 2, 40, TRUE, FALSE, FALSE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.7},{"stage":"juvenile","duration_months":18,"watering_multiplier":0.85},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Algo de sequia estimula floracion"}]'::jsonb),
('local_olive', 'Olivo', 'Olea europaea', 'outdoor', 10, 7, 6, 12, 'full_sun', -8, 42, TRUE, FALSE, TRUE, '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.65},{"stage":"juvenile","duration_months":48,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Arbol establecido, muy resistente"}]'::jsonb),
('local_lemon', 'Limonero', 'Citrus x limon', 'outdoor', 5, 3, 6, 10, 'full_sun', 3, 38, FALSE, FALSE, TRUE, '[{"stage":"seedling","duration_months":12,"watering_multiplier":0.6,"description":"Esqueje o plantula, riego frecuente"},{"stage":"juvenile","duration_months":36,"watering_multiplier":0.8},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Mas agua en fructificacion"}]'::jsonb),
('local_avocado', 'Aguacate', 'Persea americana', 'outdoor', 5, 3, 6, 10, 'full_sun', 5, 38, FALSE, TRUE, TRUE, '[{"stage":"seedling","duration_months":6,"watering_multiplier":0.6,"description":"Hueso o plantula, mantener humedo"},{"stage":"juvenile","duration_months":36,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Da fruto a partir de 5+ anios"}]'::jsonb),
('local_sunflower', 'Girasol', 'Helianthus annuus', 'outdoor', 3, 2, 6, 12, 'full_sun', 8, 38, FALSE, FALSE, FALSE, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Planta anual, florece y muere"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 6. INSERT TOMATO VARIETIES
-- ============================================================================

INSERT INTO species_catalog (id, parent_id, common_name, scientific_name, category, description, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, is_edible, hot_weather_multiplier, growth_phases) VALUES
('local_tomato_cherry', 'local_tomato', 'Tomate cherry', 'Solanum lycopersicum var. cerasiforme', 'outdoor', 'Frutos pequeños, muy productivo. Ideal macetas y balcones. Mas resistente a enfermedades.', 3, 2, 6, 10, 'full_sun', 10, 38, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.6},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.75},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb),
('local_tomato_raf', 'local_tomato', 'Tomate RAF', 'Solanum lycopersicum (RAF)', 'outdoor', 'Variedad española gourmet. Sabor intenso. Necesita suelos algo salinos. Mas exigente en riego y nutricion.', 2, 1, 6, 10, 'full_sun', 12, 32, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.55},{"stage":"juvenile","duration_months":2,"watering_multiplier":0.7},{"stage":"adult","duration_months":0,"watering_multiplier":1.0}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 7. INSERT NEW CANNABIS VARIETIES (autos + hybrids)
-- ============================================================================

INSERT INTO species_catalog (id, parent_id, common_name, scientific_name, category, description, watering_frequency_indoor, watering_frequency_outdoor, sunlight_hours_min, sunlight_hours_max, sunlight_level, min_temperature, max_temperature, humidity_loving, hot_weather_multiplier, growth_phases) VALUES
('local_cannabis_auto_northern', 'local_cannabis', 'Northern Lights Auto', 'Cannabis sativa (NL Auto)', 'cannabis', 'Autofloreciente. Ciclo completo 8-10 semanas. No depende del fotoperiodo. Ideal principiantes.', 3, 2, 12, 20, 'full_sun', 16, 28, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5,"description":"Germinacion 1-2 semanas"},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7,"description":"Vegetativo 2-3 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 5-6 semanas"}]'::jsonb),
('local_cannabis_auto_critical', 'local_cannabis', 'Critical Auto', 'Cannabis sativa (Critical Auto)', 'cannabis', 'Autofloreciente. Ciclo 9-10 semanas. Alta produccion para auto. Compacta.', 3, 2, 12, 20, 'full_sun', 16, 28, TRUE, 0.5, '[{"stage":"seedling","duration_months":1,"watering_multiplier":0.5},{"stage":"juvenile","duration_months":1,"watering_multiplier":0.7,"description":"Vegetativo 2-3 semanas"},{"stage":"adult","duration_months":0,"watering_multiplier":1.0,"description":"Floracion 6-7 semanas"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;
