-- ============================================================================
-- Migration 010: AI Care Info Cache
-- ============================================================================
-- Caches care information generated by LLM text for each plant species.
-- Keyed by scientific_name. Reduces LLM costs (cache hit = free).
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_care_cache (
  scientific_name TEXT PRIMARY KEY,
  care_info       JSONB NOT NULL,
  hit_count       INT  NOT NULL DEFAULT 1,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_ai_care_cache_created
  ON ai_care_cache (created_at DESC);

-- ============================================================================
-- RPC: increment_care_cache_hit
-- Increments the hit counter when a cached entry is used.
-- ============================================================================
CREATE OR REPLACE FUNCTION increment_care_cache_hit(p_scientific_name TEXT)
RETURNS void AS $$
BEGIN
  UPDATE ai_care_cache
  SET hit_count = hit_count + 1,
      updated_at = NOW()
  WHERE scientific_name = p_scientific_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant access to authenticated users (Edge Functions use service role)
GRANT SELECT, INSERT, UPDATE ON ai_care_cache TO authenticated;
GRANT EXECUTE ON FUNCTION increment_care_cache_hit TO authenticated;
